name: Sync Notion to GitHub

# on:
#   schedule:
#     - cron: '50 23 * * *'  # 매일 23:50에 실행
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python -m pip install notion-client

      - name: Run Sync Script
        env:
          NOTION_API_TOKEN: ${{ secrets.API_TOKEN_NOTION }}
          GITHUB_API_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          NOTION_PAGE_ID: ${{ vars.NOTION_PAGE_ID }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          REPO_README_PATH: ${{ vars.REPO_README_PATH }}
        run: python .github/scripts/sync.py  # 스크립트의 경로와 이름을 실제 스크립트에 맞게 수정